version: '3'

services:
  broker-service:
    build:
      context: ./broker-service
      dockerfile: ./broker-service.dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1

  authentication-service:
    build:
      context: ./authentication-service
      dockerfile: ./authentication-service.dockerfile
    restart: always
    ports:
      - "8081:80"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=cuongnt password=25011998aA@ dbname=micro_go_db sslmode=disable timezone=UTC connect_timeout=5"

  logger-service:
    build:
      context: ./logger-service
      dockerfile: ./logger-service.dockerfile
    restart: always
      - "8083:80"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MONGO_USER_NAME: "cuongnt"
      MONGO_PASSWORD: "25011998"

  mail-service:
    build:
      context: ./mail-service
      dockerfile: ./mail-service.dockerfile
    restart: always
    ports:
      - "8082:80"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MAIL_DOMAIN: "localhost"
      MAIL_HOST: "mail-hog"
      MAIL_PORT: 1025
      MAIL_USER_NAME: ""
      MAIL_PASSWORD: ""
      MAIL_ENCRYPTION: "none"
      MAIL_FROM_NAME: "Cuong Nguyen"
      MAIL_FROM_ADDRESS: "cuongnt.blockhive@gmail.com"

  postgres:
    image: 'postgres:14.2'
    ports:
      - "5431:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: cuongnt
      POSTGRES_PASSWORD: 25011998aA@
      POSTGRES_DB: micro_go_db
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/

  mongo:
    image: 'mongo:4.2.16-bionic'
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: logs
      MONGO_INITDB_ROOT_USERNAME: cuongnt
      MONGO_INITDB_ROOT_PASSWORD: 25011998aA@
    volumes:
      - ./db-data/mongo/:/data/db

  mail-hog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
